### ISSUE TITLE
Accidentally pushed a commit to QA branch

### ISSUE THREAD

**Issue by shussain** [hres/cfg-task-service#4]
I accidentally pushed a commit to the hres/cfg-tas-service repo's QA branch. I had intended to push it to my forked repo and make a proper Pull request.

The commit is 5de99c426eed7985865f659e1a10208ed50811ee and it  renaming cfg-task-service in pom.xml file in the QA branch. The purpose of that commit is to allow the QA branch to have a different JAR name. This will make it easier to deploy this particular branch.

Sorry about the direct push rather than creating a pull request. If you wish me to revert the change, I can.

**Comment by rsanchej** [comment]
Sure, if you could revert it that would be great.  On another topic, any idea why cfg-task-service dev is out of commision?  I've checked in changes a few times and it still does not seem to rebuild/redeploy?

**Comment by shussain** [comment]
> Sure, if you could revert it that would be great. 

Reverted the change.

I will need the change made in order to be able to deploy cfg-task-service-qa at some point so can you please review commit 5de99c4 so that the change can be persisted in the QA branch.

> On  another topic, any idea why cfg-task-service dev is out of commision?   I've checked in changes a few times and it still does not seem to  rebuild/redeploy?

There were 3 failed builds (today at 10:32, 10:40 and 11:02). There was a compile error of: _/opt/maven/cfg-task-service/src/main/java/ca/gc/ip346/util/RequestURL.java:[7,8] class RequestURI is public, should be declared in a file named RequestURI.java_ and _/opt/maven/cfg-task-service/src/main/java/ca/gc/ip346/classification/resource/FoodsResource.java:[98,24] cannot find symbol
  symbol:   class RequestURI_

The latest build at 13:32 passed so the issue seems to have been resolved.

**Comment by rsanchej** [comment]
Apparently, it still not deploying.  Any call still give a 404.

**Comment by shussain** [comment]
I forced a deployment and it all seems to be working now.   https://java-dev.hres.ca/cfg-task-service/ is back up.

**Comment by shussain** [comment]
@rsanchej Assuming the java-dev issue has been fixed. Since the original issue has been fixed, closing this issue and opened issue #5 about assessing the pom.xml change to QA branch
